/*
 * This file is generated by jOOQ.
 */
package net.yewton.petclinic.jooq.tables


import kotlin.collections.Collection

import net.yewton.petclinic.jooq.Public
import net.yewton.petclinic.jooq.keys.CONSTRAINT_256
import net.yewton.petclinic.jooq.keys.CONSTRAINT_4C
import net.yewton.petclinic.jooq.tables.Pets.PetsPath
import net.yewton.petclinic.jooq.tables.records.TypesRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Types(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TypesRecord>?,
    parentPath: InverseForeignKey<out Record, TypesRecord>?,
    aliased: Table<TypesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TypesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.TYPES</code>
         */
        val TYPES: Types = Types()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TypesRecord> = TypesRecord::class.java

    /**
     * The column <code>PUBLIC.TYPES.ID</code>.
     */
    val ID: TableField<TypesRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>PUBLIC.TYPES.NAME</code>.
     */
    val NAME: TableField<TypesRecord, String?> = createField(DSL.name("NAME"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<TypesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TypesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TypesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PUBLIC.TYPES</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.TYPES</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.TYPES</code> table reference
     */
    constructor(): this(DSL.name("TYPES"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TypesRecord>?, parentPath: InverseForeignKey<out Record, TypesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TYPES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TypesPath : Types, Path<TypesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TypesRecord>?, parentPath: InverseForeignKey<out Record, TypesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TypesRecord>): super(alias, aliased)
        override fun `as`(alias: String): TypesPath = TypesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TypesPath = TypesPath(alias, this)
        override fun `as`(alias: Table<*>): TypesPath = TypesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<TypesRecord, Int?> = super.getIdentity() as Identity<TypesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TypesRecord> = CONSTRAINT_4C

    private lateinit var _pets: PetsPath

    /**
     * Get the implicit to-many join path to the <code>PUBLIC.PETS</code> table
     */
    fun pets(): PetsPath {
        if (!this::_pets.isInitialized)
            _pets = PetsPath(this, null, CONSTRAINT_256.inverseKey)

        return _pets;
    }

    val pets: PetsPath
        get(): PetsPath = pets()
    override fun `as`(alias: String): Types = Types(DSL.name(alias), this)
    override fun `as`(alias: Name): Types = Types(alias, this)
    override fun `as`(alias: Table<*>): Types = Types(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Types = Types(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Types = Types(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Types = Types(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Types = Types(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Types = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Types = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Types = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Types = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Types = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Types = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Types = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Types = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Types = where(DSL.notExists(select))
}
