/*
 * This file is generated by jOOQ.
 */
package net.yewton.petclinic.jooq.tables


import kotlin.collections.Collection
import kotlin.collections.List

import net.yewton.petclinic.jooq.Public
import net.yewton.petclinic.jooq.keys.CONSTRAINT_7
import net.yewton.petclinic.jooq.keys.CONSTRAINT_7A
import net.yewton.petclinic.jooq.keys.CONSTRAINT_7AC
import net.yewton.petclinic.jooq.tables.Specialties.SpecialtiesPath
import net.yewton.petclinic.jooq.tables.Vets.VetsPath
import net.yewton.petclinic.jooq.tables.records.VetSpecialtiesRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VetSpecialties(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VetSpecialtiesRecord>?,
    parentPath: InverseForeignKey<out Record, VetSpecialtiesRecord>?,
    aliased: Table<VetSpecialtiesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VetSpecialtiesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.VET_SPECIALTIES</code>
         */
        val VET_SPECIALTIES: VetSpecialties = VetSpecialties()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VetSpecialtiesRecord> = VetSpecialtiesRecord::class.java

    /**
     * The column <code>PUBLIC.VET_SPECIALTIES.VET_ID</code>.
     */
    val VET_ID: TableField<VetSpecialtiesRecord, Int?> = createField(DSL.name("VET_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>PUBLIC.VET_SPECIALTIES.SPECIALTY_ID</code>.
     */
    val SPECIALTY_ID: TableField<VetSpecialtiesRecord, Int?> = createField(DSL.name("SPECIALTY_ID"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<VetSpecialtiesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VetSpecialtiesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VetSpecialtiesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PUBLIC.VET_SPECIALTIES</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.VET_SPECIALTIES</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.VET_SPECIALTIES</code> table reference
     */
    constructor(): this(DSL.name("VET_SPECIALTIES"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VetSpecialtiesRecord>?, parentPath: InverseForeignKey<out Record, VetSpecialtiesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VET_SPECIALTIES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VetSpecialtiesPath : VetSpecialties, Path<VetSpecialtiesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VetSpecialtiesRecord>?, parentPath: InverseForeignKey<out Record, VetSpecialtiesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VetSpecialtiesRecord>): super(alias, aliased)
        override fun `as`(alias: String): VetSpecialtiesPath = VetSpecialtiesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VetSpecialtiesPath = VetSpecialtiesPath(alias, this)
        override fun `as`(alias: Table<*>): VetSpecialtiesPath = VetSpecialtiesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getUniqueKeys(): List<UniqueKey<VetSpecialtiesRecord>> = listOf(CONSTRAINT_7AC)
    override fun getReferences(): List<ForeignKey<VetSpecialtiesRecord, *>> = listOf(CONSTRAINT_7, CONSTRAINT_7A)

    private lateinit var _vets: VetsPath

    /**
     * Get the implicit join path to the <code>PUBLIC.VETS</code> table.
     */
    fun vets(): VetsPath {
        if (!this::_vets.isInitialized)
            _vets = VetsPath(this, CONSTRAINT_7, null)

        return _vets;
    }

    val vets: VetsPath
        get(): VetsPath = vets()

    private lateinit var _specialties: SpecialtiesPath

    /**
     * Get the implicit join path to the <code>PUBLIC.SPECIALTIES</code> table.
     */
    fun specialties(): SpecialtiesPath {
        if (!this::_specialties.isInitialized)
            _specialties = SpecialtiesPath(this, CONSTRAINT_7A, null)

        return _specialties;
    }

    val specialties: SpecialtiesPath
        get(): SpecialtiesPath = specialties()
    override fun `as`(alias: String): VetSpecialties = VetSpecialties(DSL.name(alias), this)
    override fun `as`(alias: Name): VetSpecialties = VetSpecialties(alias, this)
    override fun `as`(alias: Table<*>): VetSpecialties = VetSpecialties(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VetSpecialties = VetSpecialties(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VetSpecialties = VetSpecialties(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VetSpecialties = VetSpecialties(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VetSpecialties = VetSpecialties(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VetSpecialties = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VetSpecialties = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VetSpecialties = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VetSpecialties = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VetSpecialties = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VetSpecialties = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VetSpecialties = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VetSpecialties = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VetSpecialties = where(DSL.notExists(select))
}
