/*
 * This file is generated by jOOQ.
 */
package net.yewton.petclinic.jooq.tables


import kotlin.collections.Collection

import net.yewton.petclinic.jooq.Public
import net.yewton.petclinic.jooq.keys.CONSTRAINT_2
import net.yewton.petclinic.jooq.keys.CONSTRAINT_7
import net.yewton.petclinic.jooq.tables.Specialties.SpecialtiesPath
import net.yewton.petclinic.jooq.tables.VetSpecialties.VetSpecialtiesPath
import net.yewton.petclinic.jooq.tables.records.VetsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Vets(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VetsRecord>?,
    parentPath: InverseForeignKey<out Record, VetsRecord>?,
    aliased: Table<VetsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VetsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.VETS</code>
         */
        val VETS: Vets = Vets()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VetsRecord> = VetsRecord::class.java

    /**
     * The column <code>PUBLIC.VETS.ID</code>.
     */
    val ID: TableField<VetsRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>PUBLIC.VETS.FIRST_NAME</code>.
     */
    val FIRST_NAME: TableField<VetsRecord, String?> = createField(DSL.name("FIRST_NAME"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>PUBLIC.VETS.LAST_NAME</code>.
     */
    val LAST_NAME: TableField<VetsRecord, String?> = createField(DSL.name("LAST_NAME"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<VetsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VetsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VetsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PUBLIC.VETS</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.VETS</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.VETS</code> table reference
     */
    constructor(): this(DSL.name("VETS"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VetsRecord>?, parentPath: InverseForeignKey<out Record, VetsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VETS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VetsPath : Vets, Path<VetsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VetsRecord>?, parentPath: InverseForeignKey<out Record, VetsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VetsRecord>): super(alias, aliased)
        override fun `as`(alias: String): VetsPath = VetsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VetsPath = VetsPath(alias, this)
        override fun `as`(alias: Table<*>): VetsPath = VetsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<VetsRecord, Int?> = super.getIdentity() as Identity<VetsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<VetsRecord> = CONSTRAINT_2

    private lateinit var _vetSpecialties: VetSpecialtiesPath

    /**
     * Get the implicit to-many join path to the
     * <code>PUBLIC.VET_SPECIALTIES</code> table
     */
    fun vetSpecialties(): VetSpecialtiesPath {
        if (!this::_vetSpecialties.isInitialized)
            _vetSpecialties = VetSpecialtiesPath(this, null, CONSTRAINT_7.inverseKey)

        return _vetSpecialties;
    }

    val vetSpecialties: VetSpecialtiesPath
        get(): VetSpecialtiesPath = vetSpecialties()

    /**
     * Get the implicit many-to-many join path to the
     * <code>PUBLIC.SPECIALTIES</code> table
     */
    val specialties: SpecialtiesPath
        get(): SpecialtiesPath = vetSpecialties().specialties()
    override fun `as`(alias: String): Vets = Vets(DSL.name(alias), this)
    override fun `as`(alias: Name): Vets = Vets(alias, this)
    override fun `as`(alias: Table<*>): Vets = Vets(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Vets = Vets(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Vets = Vets(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Vets = Vets(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Vets = Vets(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Vets = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Vets = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Vets = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Vets = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Vets = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Vets = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Vets = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Vets = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Vets = where(DSL.notExists(select))
}
