/*
 * This file is generated by jOOQ.
 */
package net.yewton.petclinic.jooq.tables


import java.time.LocalDate

import kotlin.collections.Collection
import kotlin.collections.List

import net.yewton.petclinic.jooq.Public
import net.yewton.petclinic.jooq.keys.CONSTRAINT_9
import net.yewton.petclinic.jooq.keys.CONSTRAINT_96
import net.yewton.petclinic.jooq.tables.Pets.PetsPath
import net.yewton.petclinic.jooq.tables.records.VisitsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Visits(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VisitsRecord>?,
    parentPath: InverseForeignKey<out Record, VisitsRecord>?,
    aliased: Table<VisitsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VisitsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.VISITS</code>
         */
        val VISITS: Visits = Visits()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VisitsRecord> = VisitsRecord::class.java

    /**
     * The column <code>PUBLIC.VISITS.ID</code>.
     */
    val ID: TableField<VisitsRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>PUBLIC.VISITS.PET_ID</code>.
     */
    val PET_ID: TableField<VisitsRecord, Int?> = createField(DSL.name("PET_ID"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.VISITS.VISIT_DATE</code>.
     */
    val VISIT_DATE: TableField<VisitsRecord, LocalDate?> = createField(DSL.name("VISIT_DATE"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>PUBLIC.VISITS.DESCRIPTION</code>.
     */
    val DESCRIPTION: TableField<VisitsRecord, String?> = createField(DSL.name("DESCRIPTION"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<VisitsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VisitsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VisitsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PUBLIC.VISITS</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.VISITS</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.VISITS</code> table reference
     */
    constructor(): this(DSL.name("VISITS"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VisitsRecord>?, parentPath: InverseForeignKey<out Record, VisitsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VISITS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VisitsPath : Visits, Path<VisitsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VisitsRecord>?, parentPath: InverseForeignKey<out Record, VisitsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VisitsRecord>): super(alias, aliased)
        override fun `as`(alias: String): VisitsPath = VisitsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VisitsPath = VisitsPath(alias, this)
        override fun `as`(alias: Table<*>): VisitsPath = VisitsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<VisitsRecord, Int?> = super.getIdentity() as Identity<VisitsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<VisitsRecord> = CONSTRAINT_9
    override fun getReferences(): List<ForeignKey<VisitsRecord, *>> = listOf(CONSTRAINT_96)

    private lateinit var _pets: PetsPath

    /**
     * Get the implicit join path to the <code>PUBLIC.PETS</code> table.
     */
    fun pets(): PetsPath {
        if (!this::_pets.isInitialized)
            _pets = PetsPath(this, CONSTRAINT_96, null)

        return _pets;
    }

    val pets: PetsPath
        get(): PetsPath = pets()
    override fun `as`(alias: String): Visits = Visits(DSL.name(alias), this)
    override fun `as`(alias: Name): Visits = Visits(alias, this)
    override fun `as`(alias: Table<*>): Visits = Visits(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Visits = Visits(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Visits = Visits(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Visits = Visits(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Visits = Visits(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Visits = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Visits = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Visits = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Visits = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Visits = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Visits = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Visits = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Visits = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Visits = where(DSL.notExists(select))
}
