services:
  postgres:
    image: postgres:18.3@sha256:c5bd032fb659503bf121faf5cea5894dcfece30286a3db59e3c060f3e9f60cb0
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
  alloy:
    image: grafana/alloy:v1.19.2@sha256:b8ec653c44235fbe910879145dac3597d66b0aaecf60bcbbe82580767771a839
    ports:
      - "${ALLOY_MGMT_PORT:-12345}:12345" # alloy
      - "${ALLOY_OTLP_GRPC_PORT:-4317}:4317" # OTLP/gRPC
      - "${ALLOY_OTLP_HTTP_PORT:-4318}:4318" # OTLP/HTTP
#      - "12348:12348" # ???
#      - "6832:6832" # jaeger.thrift over binary thrift protocol
#      - "55679:55679" # zpages https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md
    volumes:
      - "./config/config.alloy:/etc/alloy/config.alloy"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=experimental", # livedebugging 用
      "/etc/alloy/config.alloy",
    ]
  grafana:
    image: grafana/grafana:13.2.1@sha256:f772d434e8fab0049deb2b1b30abd43342bcfca1537614aa8d36080232cf4283
    volumes:
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  mimir: # メトリクス
    image: grafana/mimir:3.2.0@sha256:736f7459913d262444e70813565e3ca24b64dce24343da20af554ae6ee5268e8
    command: ["-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml"]
    ports:
      - "${MIMIR_PORT:-9009}:9009"
    volumes:
      - "./config/mimir.yaml:/etc/mimir.yaml"
  loki: # ログ
    image: grafana/loki:3.7.7@sha256:d70e4659623f3e109af669cae76fe2a5dd5be54e2298fe8aed380d982fbc2500
    command: ["-config.file=/etc/loki/loki.yaml"]
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - "./config/loki.yaml:/etc/loki/loki.yaml"
  tempo: # トレース
    image: grafana/tempo:2.10.8@sha256:f0561deb1c68ec44d6e6e7e4487f30106c4e5e768642077695b37958b105812a
    ports:
      - "${TEMPO_PORT:-3200}:3200"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./config/tempo.yaml:/etc/tempo.yaml"
