/*
 * This file is generated by jOOQ.
 */
package net.yewton.petclinic.jooq


import kotlin.collections.List

import net.yewton.petclinic.jooq.tables.Owners
import net.yewton.petclinic.jooq.tables.Pets
import net.yewton.petclinic.jooq.tables.Specialties
import net.yewton.petclinic.jooq.tables.Types
import net.yewton.petclinic.jooq.tables.VetSpecialties
import net.yewton.petclinic.jooq.tables.Vets
import net.yewton.petclinic.jooq.tables.Visits

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("PUBLIC", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>PUBLIC</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>PUBLIC.OWNERS</code>.
     */
    val OWNERS: Owners get() = Owners.OWNERS

    /**
     * The table <code>PUBLIC.PETS</code>.
     */
    val PETS: Pets get() = Pets.PETS

    /**
     * The table <code>PUBLIC.SPECIALTIES</code>.
     */
    val SPECIALTIES: Specialties get() = Specialties.SPECIALTIES

    /**
     * The table <code>PUBLIC.TYPES</code>.
     */
    val TYPES: Types get() = Types.TYPES

    /**
     * The table <code>PUBLIC.VET_SPECIALTIES</code>.
     */
    val VET_SPECIALTIES: VetSpecialties get() = VetSpecialties.VET_SPECIALTIES

    /**
     * The table <code>PUBLIC.VETS</code>.
     */
    val VETS: Vets get() = Vets.VETS

    /**
     * The table <code>PUBLIC.VISITS</code>.
     */
    val VISITS: Visits get() = Visits.VISITS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Owners.OWNERS,
        Pets.PETS,
        Specialties.SPECIALTIES,
        Types.TYPES,
        VetSpecialties.VET_SPECIALTIES,
        Vets.VETS,
        Visits.VISITS
    )
}
