/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.io.r2dbc.r2dbc.spi)
    api(libs.com.ongres.scram.scram.client)
    api(libs.com.ongres.scram.scram.common)
    api(libs.io.projectreactor.reactor.core)
    api(libs.io.projectreactor.netty.reactor.netty.core)
    api(libs.io.netty.netty.transport.native.epoll)
    api(libs.io.netty.netty.transport.native.kqueue)
    testImplementation(libs.io.projectreactor.reactor.test)
    testImplementation(libs.io.r2dbc.r2dbc.spi.test)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.awaitility.awaitility)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.postgresql.postgresql)
    testImplementation(libs.org.springframework.spring.jdbc)
    testImplementation(libs.com.zaxxer.hikaricp)
    testImplementation(libs.org.testcontainers.postgresql)
    testImplementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.org.junit.platform.junit.platform.launcher)
    compileOnly(libs.com.google.code.findbugs.jsr305)
    compileOnly(libs.org.locationtech.jts.jts.core)
}

group = "org.postgresql"
version = "1.1.0.BUILD-SNAPSHOT"
description = "Reactive Relational Database Connectivity - Postgresql"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
