[versions]
# Spring Boot の依存バージョンに合わせる
# https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html
kotlin = "1.9.24"
jooq = "3.19.16"
opentelemetry = "2.10.0-alpha"

[libraries]
spring-boot-plugin = "org.springframework.boot:spring-boot-gradle-plugin:3.4.0"

# Spring Boot の依存バージョンに合わせる
# https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html
dependency-management-plugin = "io.spring.gradle:dependency-management-plugin:1.1.6"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
webjars-bootstrap = "org.webjars.npm:bootstrap:5.3.3"
webjars-font-awesome = "org.webjars.npm:font-awesome:4.7.0"
jooq-codegen-core = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }
jooq-meta-core = { module = "org.jooq:jooq-meta", version.ref = "jooq" }
jooq-meta-extensions = { module = "org.jooq:jooq-meta-extensions", version.ref = "jooq" }
jooq-codegen-gradle = { module = "org.jooq:jooq-codegen-gradle", version.ref = "jooq" }
jooq-postgres-extensions = { module = "org.jooq:jooq-postgres-extensions", version.ref = "jooq" }
jooq-kotlin-coroutines = { module = "org.jooq:jooq-kotlin-coroutines", version.ref = "jooq" }
spotless-plugin-gradle = "com.diffplug.spotless:spotless-plugin-gradle:6.25.0"
opentelemetry-logback-appender = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version.ref = "opentelemetry" }
opentelemetry-logback-mdc = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0", version.ref = "opentelemetry" }
