spring:
  application:
    name: petclinic
  profiles:
    default: local
  r2dbc:
    url: ${POSTGRES_URL:r2dbc:postgresql://localhost/petclinic}
    username: ${POSTGRES_USER:petclinic}
    password: ${POSTGRES_PASS:petclinic}
  messages:
    basename: messages/messages
