logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
spring:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      # SQL は冪等に書かれているのでこれでも安全
      mode: always
  docker:
    compose:
      file: @rootDir@/../docker-compose.yml
