/*
 * This file is generated by jOOQ.
 */
package net.yewton.petclinic.jooq.tables.references


import net.yewton.petclinic.jooq.tables.Owners
import net.yewton.petclinic.jooq.tables.Pets
import net.yewton.petclinic.jooq.tables.Specialties
import net.yewton.petclinic.jooq.tables.Types
import net.yewton.petclinic.jooq.tables.VetSpecialties
import net.yewton.petclinic.jooq.tables.Vets
import net.yewton.petclinic.jooq.tables.Visits



/**
 * The table <code>PUBLIC.OWNERS</code>.
 */
val OWNERS: Owners = Owners.OWNERS

/**
 * The table <code>PUBLIC.PETS</code>.
 */
val PETS: Pets = Pets.PETS

/**
 * The table <code>PUBLIC.SPECIALTIES</code>.
 */
val SPECIALTIES: Specialties = Specialties.SPECIALTIES

/**
 * The table <code>PUBLIC.TYPES</code>.
 */
val TYPES: Types = Types.TYPES

/**
 * The table <code>PUBLIC.VET_SPECIALTIES</code>.
 */
val VET_SPECIALTIES: VetSpecialties = VetSpecialties.VET_SPECIALTIES

/**
 * The table <code>PUBLIC.VETS</code>.
 */
val VETS: Vets = Vets.VETS

/**
 * The table <code>PUBLIC.VISITS</code>.
 */
val VISITS: Visits = Visits.VISITS
